#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Based on the /wizard template. Display helpers use the shared with-scripts
# terminal style; hosting and secret operations remain in the stages below.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard helpers: cyan accents and a continuous guide, matching the Node CLI.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 && -z "${NO_COLOR+x}" ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 6); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  printf '│\n%s◇%s  %s%s%s\n' "$BLUE" "$RESET" "$BOLD" "$1" "$RESET"
  note "$TOTAL_STAGES stages · Hosting access and GitHub Actions"
  say "Review each step and use Ctrl-C to stop setup."
  pause "Ready to start?"
}

# stage "Name" shows progress while keeping previous steps in the scrollback.
stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '│\n%s%s◆ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '│  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '│  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '│  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '│\n%s▲%s  %s\n' "$YELLOW" "$RESET" "$1"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '│  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '│  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '│\n%s◆%s  %s\n│  [y/N] ' "$BLUE" "$RESET" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '│\n%s◆%s  %s%s%s\n│  %s[Enter keeps current]%s ' "$BLUE" "$RESET" "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '│\n%s◆%s  %s%s%s\n│  ' "$BLUE" "$RESET" "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '│\n%s◆%s  %s%s%s\n│  %s[Enter keeps current]%s ' "$BLUE" "$RESET" "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '│\n%s◆%s  %s%s%s\n│  ' "$BLUE" "$RESET" "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish shows a closing summary of everything configured.
finish() {
  printf '│\n%s└%s  %sSetup complete%s\n' "$GREEN" "$RESET" "$BOLD" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: deployment setup. Project values are supplied by setup-deployment.mjs.

# Public project defaults live in .with-scripts.json. Secrets go only to GitHub.
ENV_FILE=/dev/null
TOTAL_STAGES=5
if [[ "${1:-}" = --demo ]]; then
  trap 'exit 130' INT
  trap 'exit 143' TERM
  say "Deployment wizard demo"
  say "All five stages use example values and simulate the setup."
  say "Press Enter to advance; Ctrl-C ends the demo."
  pause "Ready to start?"

  stage "Demo · Review project and GitHub access" || exit 1
  say "Repository: example-owner/example-site"
  say "Target: site-account@server.example.org:22/srv/site/httpdocs"
  ask DEMO_THEME "Theme slug for this walkthrough [example-theme]:"
  DEMO_THEME="${DEMO_THEME:-example-theme}"
  say "Theme: $DEMO_THEME; built plugin: none"
  say "Real setup verifies GitHub access and asks you to confirm this target."
  pause

  stage "Demo · Install a dedicated deployment key on the hosting account" || exit 1
  step "Real setup creates or reads a dedicated SSH key and opens your hosting panel."
  step "You authorize its public key for the deployment account."
  say "Example public key: ssh-ed25519 <example-public-key> deployment-demo"
  pause "Press Enter to simulate installing the public key"

  stage "Demo · Verify the server identity" || exit 1
  step "Real setup displays the server's SSH host-key fingerprints."
  step "You compare them with your host's documentation or trusted server console."
  step "You paste the independently verified SHA256 fingerprint."
  pause "Press Enter to simulate a matching fingerprint"

  stage "Demo · Check the deployment key and remote paths" || exit 1
  say "Real setup uses the dedicated key to check SSH access and WordPress paths."
  say "Theme target: /srv/site/httpdocs/wp-content/themes/$DEMO_THEME"
  say "Deployment temp directory: /srv/deployment-temp/"
  pause "Press Enter to simulate successful access and path checks"

  stage "Demo · Review and write GitHub Actions secrets" || exit 1
  say "Repository: example-owner/example-site"
  say "Secrets: HOST, USERNAME, KEY, PORT, FINGERPRINT"
  say "Real setup asks you to type SET SECRETS example-owner/example-site before writing."
  say "It then saves the release workflow and public project defaults."
  pause "Press Enter to finish the simulated setup"
  say "Demo complete. All steps were simulated; files, keys, and GitHub secrets are unchanged."
  say "For real setup, run with-scripts setup-deployment inside your website repository."
  exit 0
fi
: "${GH_REPO:?Start this wizard with with-scripts setup-deployment.}"
: "${WITH_DEPLOY_KEY:?Start this wizard with with-scripts setup-deployment.}"
[[ -t 0 && -t 1 ]] || { warn "Run setup-deployment in an interactive terminal."; exit 1; }
umask 077
wizard_temp=$(mktemp -d "${TMPDIR:-/tmp}/with-scripts-deployment.XXXXXX")
trap 'rm -rf -- "$wizard_temp"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

banner "WordPress deployment setup" || exit 1

stage "Review project and GitHub access" || exit 1
say "Repository: $GH_REPO"
say "Target: $WITH_DEPLOY_USER@$WITH_DEPLOY_HOST:$WITH_DEPLOY_PORT$WITH_DEPLOY_ROOT"
say "Theme: $WITH_DEPLOY_THEME; built plugin: $WITH_DEPLOY_PLUGIN"
say "Deployment temp directory: $WITH_DEPLOY_TEMP"
say "Private-key file: $WITH_DEPLOY_KEY"
say "The workflow deploys custom code when a release is published."
for command in gh ssh ssh-keygen ssh-keyscan; do
  command -v "$command" >/dev/null || { warn "Install $command and run setup-deployment again."; exit 1; }
done
gh auth status --hostname github.com || { warn "Run gh auth login --hostname github.com, then retry."; exit 1; }
actual_repo=$(gh repo view "$GH_REPO" --json nameWithOwner --jq .nameWithOwner) || exit 1
[[ "$(printf '%s' "$actual_repo" | tr '[:upper:]' '[:lower:]')" = "$(printf '%s' "$GH_REPO" | tr '[:upper:]' '[:lower:]')" ]] || { warn "GitHub repository verification failed."; exit 1; }
confirm "Continue with this project and target" || exit 1

stage "Install a dedicated deployment key on the hosting account" || exit 1
if [[ ! -e "$WITH_DEPLOY_KEY" ]]; then
  [[ ! -e "$WITH_DEPLOY_KEY.pub" && ! -L "$WITH_DEPLOY_KEY" ]] || { warn "A key path is already occupied. Choose another --key-file."; exit 1; }
  say "GitHub Actions uses a dedicated key without a passphrase."
  confirm "Create an Ed25519 key at $WITH_DEPLOY_KEY" || exit 1
  ssh-keygen -q -t ed25519 -N '' -C "$GH_REPO deployment" -f "$WITH_DEPLOY_KEY"
fi
[[ -f "$WITH_DEPLOY_KEY" && -r "$WITH_DEPLOY_KEY" && ! -L "$WITH_DEPLOY_KEY" ]] || { warn "Choose a readable regular private-key file."; exit 1; }
ssh-keygen -y -P '' -f "$WITH_DEPLOY_KEY" > "$wizard_temp/public-key" || { warn "Use a dedicated private key without a passphrase; keep your personal key in its agent."; exit 1; }
open_url "$WITH_DEPLOY_HOSTING_URL"
step "Use your host's SSH-key instructions to authorize this public key for $WITH_DEPLOY_USER:"
cat "$wizard_temp/public-key"
say "The public key belongs in that account's authorized_keys or its hosting SSH-key settings."
confirm "The public key is installed for $WITH_DEPLOY_USER" || exit 1

stage "Verify the server identity" || exit 1
say "Compare the SHA256 host-key fingerprint with your hosting provider or a trusted server console."
say "The scan below discovers keys; the trusted source establishes which key belongs to your server."
ssh-keyscan -T 10 -p "$WITH_DEPLOY_PORT" "$WITH_DEPLOY_HOST" > "$wizard_temp/host-keys" 2> "$wizard_temp/scan-errors" || { cat "$wizard_temp/scan-errors" >&2; exit 1; }
[[ -s "$wizard_temp/host-keys" ]] || { warn "The server returned no host keys. Check hostname and port."; exit 1; }
ssh-keygen -lf "$wizard_temp/host-keys" -E sha256
ask DEPLOY_FINGERPRINT "Paste the fingerprint verified through the trusted source:"
[[ "$DEPLOY_FINGERPRINT" =~ ^SHA256:[A-Za-z0-9+/]+={0,2}$ ]] || { warn "Enter a SHA256 host-key fingerprint."; exit 1; }
: > "$wizard_temp/known-hosts"
while IFS= read -r host_key; do
  [[ -n "$host_key" && "$host_key" != \#* ]] || continue
  printf '%s\n' "$host_key" > "$wizard_temp/candidate-key"
  key_info=$(ssh-keygen -lf "$wizard_temp/candidate-key" -E sha256) || exit 1
  if [[ "$key_info" = *" $DEPLOY_FINGERPRINT "* ]]; then
    printf '%s\n' "$host_key" >> "$wizard_temp/known-hosts"
  fi
done < "$wizard_temp/host-keys"
[[ -s "$wizard_temp/known-hosts" ]] || { warn "The trusted fingerprint does not match a scanned host key. Check the host and port before retrying."; exit 1; }

stage "Check the deployment key and remote paths" || exit 1
say "Checking access with the dedicated key and the verified server host key."
ssh -F /dev/null -o BatchMode=yes -o ConnectTimeout=15 -o IdentitiesOnly=yes \
  -o IdentityAgent=none -o StrictHostKeyChecking=yes \
  -o "UserKnownHostsFile=$wizard_temp/known-hosts" -o GlobalKnownHostsFile=/dev/null \
  -i "$WITH_DEPLOY_KEY" -p "$WITH_DEPLOY_PORT" "$WITH_DEPLOY_USER@$WITH_DEPLOY_HOST" \
  sh -s -- "$WITH_DEPLOY_ROOT" "$WITH_DEPLOY_TEMP" "$WITH_DEPLOY_THEME" "$WITH_DEPLOY_PLUGIN" <<'REMOTE'
set -eu
root=$1
temp=$2
theme=$3
plugin=$4
test -f "$root/wp-config.php" && test -f "$root/wp-load.php" || { echo 'Target must contain an installed WordPress site.' >&2; exit 1; }
physical_root=$(cd "$root" && pwd -P)
physical_temp=$(cd "$temp" && pwd -P)
case "$physical_temp/" in "$physical_root/"*) echo 'Deployment temp directory resolves inside the web root.' >&2; exit 1 ;; esac
test -w "$temp" && test -x "$temp" || { echo 'Deployment temp directory must be writable and accessible.' >&2; exit 1; }
for target in "$root/wp-content/themes/$theme"; do
  test ! -L "$target" || { echo 'Theme deployment target is a symbolic link.' >&2; exit 1; }
  if test -d "$target"; then test -w "$target"; else test -w "$root/wp-content/themes"; fi
done
if test "$plugin" != none; then
  target="$root/wp-content/plugins/$plugin"
  test ! -L "$target" || { echo 'Plugin deployment target is a symbolic link.' >&2; exit 1; }
  if test -d "$target"; then test -w "$target"; else test -w "$root/wp-content/plugins"; fi
fi
command -v tar >/dev/null
echo 'Dedicated-key login and deployment paths verified.'
REMOTE

stage "Review and write GitHub Actions secrets" || exit 1
open_url "https://github.com/$GH_REPO/settings/secrets/actions"
say "Repository: $GH_REPO"
say "HOST=$WITH_DEPLOY_HOST; USERNAME=$WITH_DEPLOY_USER; PORT=$WITH_DEPLOY_PORT"
say "FINGERPRINT=$DEPLOY_FINGERPRINT"
say "KEY will be read directly from $WITH_DEPLOY_KEY."
say "These five repository secrets will be created or replaced."
ask DEPLOY_APPROVAL "Type SET SECRETS $GH_REPO to continue:"
[[ "$DEPLOY_APPROVAL" = "SET SECRETS $GH_REPO" ]] || { warn "Stopped before changing GitHub secrets."; exit 1; }
# The same key must be tested and uploaded, even after a long manual pause.
ssh-keygen -y -P '' -f "$WITH_DEPLOY_KEY" > "$wizard_temp/current-public-key"
cmp -s "$wizard_temp/public-key" "$wizard_temp/current-public-key" || { warn "The key changed during setup. Run the checks again."; exit 1; }
secret_names=(HOST USERNAME PORT FINGERPRINT)
secret_values=("$WITH_DEPLOY_HOST" "$WITH_DEPLOY_USER" "$WITH_DEPLOY_PORT" "$DEPLOY_FINGERPRINT")
for index in 0 1 2 3; do
  set_secret "${secret_names[$index]}" "${secret_values[$index]}"
  if (( ${#SKIPPED[@]} )); then
    warn "Setup incomplete. A required secret could not be saved; earlier secrets may already be updated. Retry after checking repository permissions."
    exit 1
  fi
done
# Preserve every line of the private key, and keep it out of argv and .env.
gh secret set KEY --repo "$GH_REPO" < "$WITH_DEPLOY_KEY" || { warn "Setup incomplete. KEY could not be saved; the other four secrets were updated."; exit 1; }
WRITTEN_SECRET+=(KEY)
gh secret list --repo "$GH_REPO" --json name --jq '.[].name' > "$wizard_temp/secret-names"
for secret_name in HOST USERNAME KEY PORT FINGERPRINT; do
  grep -Fxq "$secret_name" "$wizard_temp/secret-names" || { warn "Setup incomplete. GitHub did not list $secret_name after writing it."; exit 1; }
done
say "All five GitHub secrets are present. SSH access and paths were verified."
say "Returning to write the reviewed local workflow and project settings."
